MovieManagement.Web/Areas/API/Controllers/CategoryController.cs
using MovieManagement.DataContracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MovieManagement.Web.Areas.API.Controllers
{
    [RoutePrefix("api/categories")]
    public class CategoryController : ApiController
    {
        private MovieManagement.Management.CategoryManagement _management = new MovieManagement.Management.CategoryManagement();

        [HttpGet]
        [Route("Search")]
        public List<CategoryDTO> Search()
        {
            return _management.Search();
        }

        [HttpDelete]
        [Route("{id}")]
        public void Delete(Guid id)
        {
            _management.DeleteCategory(id);
        }

        [HttpGet]
        [Route("{id}")]
        public CategoryDTO GetCategory(Guid id)
        {
            return _management.GetCategory(id);
        }

        [HttpPut]
        [Route("{id}")]
        public void UpdateCategory([FromBody]CategoryDTO category, Guid id)
        {
            category.Id = id;
            _management.AddOrUpdate(category);
        }

        [HttpPost]
        [Route("")]
        public void Save([FromBody]CategoryDTO category)
        {
            _management.AddOrUpdate(category);
        }
    }
}

MovieManagement.Web/Areas/API/Controllers/MovieController.cs
using MovieManagement.DataContracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MovieManagement.Web.Areas.API.Controllers
{
    [RoutePrefix("api/movies")]
    public class MovieController : ApiController
    {
        private MovieManagement.Management.MovieManagement _management = new MovieManagement.Management.MovieManagement();

        [HttpGet]
        [Route("Search")]
        public List<MovieDTO> Search()
        {
            return _management.Search();
        }

        [HttpDelete]
        [Route("{id}")]
        public void Delete(Guid id)
        {
            _management.DeleteMovie(id);
        }

        [HttpGet]
        [Route("{id}")]
        public MovieDTO GetMovie(Guid id)
        {
            return _management.GetMovie(id);
        }

        [HttpPut]
        [Route("{id}")]
        public void UpdateMovie([FromBody]MovieDTO movie, Guid id)
        {
            movie.Id = id;
            _management.AddOrUpdate(movie);
        }

        [HttpPost]
        [Route("")]
        public void SaveMovie([FromBody]MovieDTO movie)
        {
            _management.AddOrUpdate(movie);
        }
    }
}

MovieManagement.Web/Areas/API/Controllers/ReviewController.cs
using MovieManagement.DataContracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace MovieManagement.Web.Areas.API.Controllers
{
    [RoutePrefix("api/reviews")]
    public class ReviewController : ApiController
    {
        private MovieManagement.Management.ReviewManagement _management = new MovieManagement.Management.ReviewManagement();

        [HttpGet]
        [Route("Search")]
        public List<ReviewDTO> Search()
        {
            return _management.Search();
        }

        [HttpDelete]
        [Route("{id}")]
        public void Delete(Guid id)
        {
            _management.DeleteReview(id);
        }

        [HttpGet]
        [Route("{id}")]
        public ReviewDTO GetReview(Guid id)
        {
            return _management.GetReview(id);
        }

        [HttpPut]
        [Route("{id}")]
        public void UpdateReview([FromBody]ReviewDTO review, Guid id)
        {
            review.Id = id;
            _management.AddOrUpdate(review);
        }

        [HttpPost]
        [Route("")]
        public void Save([FromBody]ReviewDTO review)
        {
            _management.AddOrUpdate(review);
        }
    }
}

MovieManagement.Web/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieManagement.Web.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Movies
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(Guid id)
        {
            return View(id);
        }

        public ActionResult Create()
        {
            return View();
        }
    }
}

MovieManagement.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieManagement.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MovieManagement.Web/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieManagement.Web.Controllers
{
    public class MoviesController : Controller
    {
        // GET: Movies
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(Guid id)
        {
            return View(id);
        }

        public ActionResult Create()
        {
            return View();
        }
    }
}

MovieManagement.Web/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieManagement.Web.Controllers
{
    public class ReviewsController : Controller
    {
        // GET: Movies
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(Guid id)
        {
            return View(id);
        }
        public ActionResult Create()
        {
            return View();
        }
    }
}

MovieManagement.Web/Views/Categories/Create.cshtml
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label>Name</label>
            <input type="text" class="form-control" id="category-name" />
        </div>
    </div>

    <hr />
    <div class="col-sm-12">
        <div class="form-group">
            <button type="button" id="save-btn">Save</button>
        </div>
    </div>
</div>


@section scripts{
    <script type="text/javascript">
        $("#save-btn").click(function ()
        {
            var request = {
                Name: $("#category-name").val(),
            };

             $.ajax({
                url: 'http://localhost:56702/api/categories',
                method: 'POST',
                 data: request,
                success: function ()
                {
                    window.location.href = "/categories";
                },
                error: function (err)
                {
                    alert('update error');
                }
            })
        })
    </script>
}

MovieManagement.Web/Views/Categories/Details.cshtml
@model Guid

<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label>Name</label>
            <input type="text" class="form-control" id="category-name" />
        </div>
    </div>

    <hr />
    <div class="col-sm-12">
        <div class="form-group">
            <button type="button" id="update-btn">Update</button>
        </div>
    </div>
</div>


@section scripts{

    <script type="text/javascript">
        $.ajax({
            url: 'http://localhost:56702/api/categories/'+ '@Model',
            method: 'GET',
            success: function (data)
            {
                $('#category-name').val(data.Name);
            },
            error: function (err)
            {
                alert('error', err);
            }
        })

        $('#update-btn').click(function ()
        {
            var requestToSend = {
                Name: $('#category-name').val(),
                Id: '@Model'
            };

            $.ajax({
                url: 'http://localhost:56702/api/categories/' + '@Model',
                method: 'PUT',
                data: requestToSend,
                success: function ()
                {
                    alert('Nice');
                },
                error: function (err)
                {
                    alert('update error');
                }
            })

        })
    </script>

}

MovieManagement.Web/Views/Categories/Index.cshtml
<div class="table-responsive">
    <hr />
    <a class="btn btn-sm btn-info" href="@Url.Action("Create","Categories")">Add category</a>
    <hr />
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody id="categories-tbody"></tbody>
    </table>
</div>
<!-- /.table-responsive -->

@section scripts{
    <script type="text/javascript">
        $.ajax({
            url: 'http://localhost:56702/api/categories/search',
            method: 'GET',
            success: function (result)
            {
                for (var i = 0; i < result.length; i++) {
                    var newRow = "<tr><td><a href='/Categories/Details?id=" + result[i].Id + "'>" + result[i].Name + "</a></td><td><button class='btn btn-default delete' data-id='" + result[i].Id + "'>Delete</button></td></tr>";
                    $("#categories-tbody").append(newRow);
                }

                $('.delete').click(function ()
                {
                    //click event body

                    var id = $(this).data('id');
                    var tr = $(this).parent().parent();

                    $.ajax({
                        url: 'http://localhost:56702/api/categories/' + id,
                        method: 'DELETE',
                        success: function ()
                        {
                            tr.hide('slow', function ()
                            {
                                tr.remove();
                            })
                        },
                        error: function (err)
                        {
                            alert('delete error');
                        }
                    })
                });
            },
            error: function (err)
            {
                alert('error');
            }
        })
    </script>
}

MovieManagement.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MovieManagement.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MovieManagement.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div class="row">
        <div class="col-md-4">
            <h2>Movie Management</h2>
        </div>
    </div>
</div>

MovieManagement.Web/Views/Movies/Create.cshtml
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label>Title</label>
            <input type="text" class="form-control" id="movie-title" />
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            <label>Rating</label>
            <input type="text" class="form-control" id="movie-rating" />
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            <label>Category</label>
            <select id="movie-category">
            </select>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            <label>ReleaseDate</label>
            <input type="date" class="form-control" id="movie-date" value="2018-05-05"/>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            <label>Length</label>
            <input type="number" class="form-control" id="movie-length" value="120" />
        </div>
    </div>

    <hr />
    <div class="col-sm-12">
        <div class="form-group">
            <button type="button" id="save-btn">Save</button>
        </div>
    </div>
</div>


@section scripts{
    <script type="text/javascript">
        $.ajax({
            url: 'http://localhost:56702/api/categories/search',
            method: 'GET',
            success: function (result)
            {
                for (var i = 0; i < result.length; i++)
                {
                    var newOption = "<option value='"+result[i].Name+"'>"+result[i].Name+"</option>";
                    $("#movie-category").append(newOption);
                }
            },
            error: function (err)
            {
                alert('error');
            }
        })


        $("#save-btn").click(function ()
        {
            var request = {
                Title: $("#movie-title").val(),
                Rating: $("#movie-rating").val(),
                CategoryName: $("#movie-category").val(),
                ReleaseDate: $("#movie-date").val(),
                Length: $("#movie-length").val(),
            };

             $.ajax({
                url: 'http://localhost:56702/api/movies',
                method: 'POST',
                 data: request,
                success: function ()
                {
                    window.location.href = "/movies";
                },
                error: function (err)
                {
                    alert('update error');
                }
            })
        })
    </script>
}

MovieManagement.Web/Views/Movies/Details.cshtml
@model Guid

<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label>Title</label>
            <input type="text" class="form-control" id="movie-title" />
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            <label>Rating</label>
            <input type="text" class="form-control" id="movie-rating" />
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            <label>Category</label>
            <span id="movie-category"></span>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            <label>ReleaseDate</label>
            <span id="movie-date"></span>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            <label>Length</label>
            <span id="movie-length"></span>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            <label>Score</label>
            <span id="movie-score"></span>
        </div>
    </div>

    <hr />
    <div class="col-sm-12">
        <div class="form-group">
            <button type="button" id="update-btn">Update</button>
        </div>
    </div>
</div>


@section scripts{

    <script type="text/javascript">
        $.ajax({
            url: 'http://localhost:56702/api/movies/'+ '@Model',
            method: 'GET',
            success: function (data)
            {
                $('#movie-title').val(data.Title);
                $('#movie-rating').val(data.Rating);
                $('#movie-category').text(data.CategoryName);
                $('#movie-date').text(data.ReleaseDate);
                $('#movie-length').text(data.Length);
                $('#movie-score').text(data.AverageScore);
            },
            error: function (err)
            {
                alert('error', err);
            }
        })

        $('#update-btn').click(function ()
        {
            var requestToSend = {
                Title: $('#movie-title').val(),
                Rating: $('#movie-rating').val(),
                ReleaseDate: $('#movie-date').text(),
                Length: $('#movie-length').text(),
                Id: '@Model'
            };

            $.ajax({
                url: 'http://localhost:56702/api/movies/' + '@Model',
                method: 'PUT',
                data: requestToSend,
                success: function ()
                {
                    alert('Nice');
                },
                error: function (err)
                {
                    alert('update error');
                }
            })

        })
    </script>

}

MovieManagement.Web/Views/Movies/Index.cshtml
<div class="table-responsive">
    <hr />
    <a class="btn btn-sm btn-info" href="@Url.Action("Create","Movies")">Add movie</a>
    <hr />
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Category</th>
                <th>Rating</th>
                <th>Score</th>
                <th>Release Date</th>
                <th></th>
            </tr>
        </thead>
        <tbody id="movies-tbody">
        </tbody>
    </table>
</div>
<!-- /.table-responsive -->

@section scripts{
    <script type="text/javascript">
        $.ajax({
            url: 'http://localhost:56702/api/movies/search',
            method: 'GET',
            success: function (result)
            {
                for (var i = 0; i < result.length; i++) {
                    var newRow = "<tr><td><a href='/Movies/Details?id=" + result[i].Id + "'>" + result[i].Title + "</a></td><td>" + result[i].CategoryName + "</td><td>" + result[i].Rating + "</td><td>" + result[i].AverageScore + "</td><td>" + result[i].ReleaseDate + "</td><td><button class='btn btn-default delete' data-id='" + result[i].Id + "'>Delete</button></td></tr>";
                    $("#movies-tbody").append(newRow);
                }

                $('.delete').click(function ()
                {
                    //click event body

                    var id = $(this).data('id');
                    var tr = $(this).parent().parent();

                    $.ajax({
                        url: 'http://localhost:56702/api/movies/' + id,
                        method: 'DELETE',
                        success: function ()
                        {
                            tr.hide('slow', function ()
                            {
                                tr.remove();
                            })
                        },
                        error: function (err)
                        {
                            alert('delete error');
                        }
                    })
                });
            },
            error: function (err)
            {
                alert('error');
            }
        })
    </script>
}

MovieManagement.Web/Views/Reviews/Create.cshtml
<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label>Score</label>
            <input type="text" class="form-control" id="review-score" />
        </div>
    </div>

    <hr />
    <div class="col-sm-12">
        <div class="form-group">
            <button type="button" id="save-btn">Save</button>
        </div>
    </div>
</div>


@section scripts{
    <script type="text/javascript">
        $("#save-btn").click(function ()
        {
            var request = {
                Score: $("#review-score").val(),
            };

             $.ajax({
                url: 'http://localhost:56702/api/reviews',
                method: 'POST',
                 data: request,
                success: function ()
                {
                    window.location.href = "/reviews";
                },
                error: function (err)
                {
                    alert('update error');
                }
            })
        })
    </script>
}

MovieManagement.Web/Views/Reviews/Details.cshtml
@model Guid

<div class="row">
    <div class="col-sm-12">
        <div class="form-group">
            <label>Score</label>
            <input type="text" class="form-control" id="review-score" />
        </div>
    </div>

    <hr />
    <div class="col-sm-12">
        <div class="form-group">
            <button type="button" id="update-btn">Update</button>
        </div>
    </div>
</div>


@section scripts{

    <script type="text/javascript">
        $.ajax({
            url: 'http://localhost:56702/api/reviews/'+ '@Model',
            method: 'GET',
            success: function (data)
            {
                $('#review-score').val(data.Score);
            },
            error: function (err)
            {
                alert('error', err);
            }
        })

        $('#update-btn').click(function ()
        {
            var requestToSend = {
                Score: $('#review-score').val(),
                Id: '@Model'
            };

            $.ajax({
                url: 'http://localhost:56702/api/reviews/' + '@Model',
                method: 'PUT',
                data: requestToSend,
                success: function ()
                {
                    alert('Nice');
                },
                error: function (err)
                {
                    alert('update error');
                }
            })

        })
    </script>

}

MovieManagement.Web/Views/Reviews/Index.cshtml
<div class="table-responsive">
    <hr />
    <a class="btn btn-sm btn-info" href="@Url.Action("Create","Reviews")">Add review score</a>
    <hr />
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>Score</th>
                <th></th>
            </tr>
        </thead>
        <tbody id="reviews-tbody"></tbody>
    </table>
</div>
<!-- /.table-responsive -->

@section scripts{
    <script type="text/javascript">
        $.ajax({
            url: 'http://localhost:56702/api/reviews/search',
            method: 'GET',
            success: function (result)
            {
                result.sort(function (a, b) { return a.Score - b.Score });

                for (var i = 0; i < result.length; i++)
                {
                    var newRow = "<tr><td><a href='/Reviews/Details?id=" + result[i].Id + "'>" + result[i].Score + "</a></td><td><button class='btn btn-default delete' data-id='" + result[i].Id + "'>Delete</button></td></tr>";
                    $("#reviews-tbody").append(newRow);
                }

                $('.delete').click(function ()
                {
                    //click event body

                    var id = $(this).data('id');
                    var tr = $(this).parent().parent();

                    $.ajax({
                        url: 'http://localhost:56702/api/reviews/' + id,
                        method: 'DELETE',
                        success: function ()
                        {
                            tr.hide('slow', function ()
                            {
                                tr.remove();
                            })
                        },
                        error: function (err)
                        {
                            alert('delete error');
                        }
                    })
                });
            },
            error: function (err)
            {
                alert('error');
            }
        })
    </script>
}

MovieManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <!-- Bootstrap Core CSS -->
    <link href="~/Theme/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/Theme/css/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Theme/css/sb-admin-2.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="~/Theme/css/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Theme/css/font-awesome.min.css" rel="stylesheet" type="text/css">

</head>
<body>

    @Html.Partial("_Navigation")
   


    <div id="wrapper">
        <div id="page-wrapper">
            @RenderBody()
        </div>

    </div>
    <!-- jQuery -->
    <script src="~/Theme/js/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Theme/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Theme/js/metisMenu.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/Theme/js/raphael.min.js"></script>
    <script src="~/Theme/js/morris.min.js"></script>
    <script src="~/Theme/js/morris-data.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Theme/js/sb-admin-2.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

MovieManagement.Web/Views/Shared/_Navigation.cshtml
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">Movie Web App</a>
    </div>

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">

                <li>
                    <a href="@Url.Action("Index","Home")"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Movies")">Movies</a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Categories")">Categories</a>
                </li>
                <li>
                    <a href="@Url.Action("Index","Reviews")">Reviews</a>
                </li>
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>